//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5483
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteLegui.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RestauranteLegui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap _06 {
            get {
                object obj = ResourceManager.GetObject("06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1464242553_cake {
            get {
                object obj = ResourceManager.GetObject("1464242553_cake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1464242559_cake_choko {
            get {
                object obj = ResourceManager.GetObject("1464242559_cake_choko", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1464243288_beer {
            get {
                object obj = ResourceManager.GetObject("1464243288_beer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1464301026_f_right_256 {
            get {
                object obj = ResourceManager.GetObject("1464301026_f-right_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1464301033_f_left_256 {
            get {
                object obj = ResourceManager.GetObject("1464301033_f-left_256", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1464301126_house {
            get {
                object obj = ResourceManager.GetObject("1464301126_house", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1464419764_Empty_Trash {
            get {
                object obj = ResourceManager.GetObject("1464419764_Empty Trash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1464468287_Apply {
            get {
                object obj = ResourceManager.GetObject("1464468287_Apply", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap _1464468291_Circulation {
            get {
                object obj = ResourceManager.GetObject("1464468291_Circulation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap anigif_candles_2056_1303504097_13 {
            get {
                object obj = ResourceManager.GetObject("anigif_candles-2056-1303504097-13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Azul1 {
            get {
                object obj = ResourceManager.GetObject("Azul1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Azul2 {
            get {
                object obj = ResourceManager.GetObject("Azul2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Azul3 {
            get {
                object obj = ResourceManager.GetObject("Azul3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Azul4 {
            get {
                object obj = ResourceManager.GetObject("Azul4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Azul5 {
            get {
                object obj = ResourceManager.GetObject("Azul5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Azul6 {
            get {
                object obj = ResourceManager.GetObject("Azul6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Azul61 {
            get {
                object obj = ResourceManager.GetObject("Azul61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Azul7 {
            get {
                object obj = ResourceManager.GetObject("Azul7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Azul8 {
            get {
                object obj = ResourceManager.GetObject("Azul8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Azul9 {
            get {
                object obj = ResourceManager.GetObject("Azul9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap b13acd00346a8e710950a803f2f45f83d0b80435 {
            get {
                object obj = ResourceManager.GetObject("b13acd00346a8e710950a803f2f45f83d0b80435", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap borrar {
            get {
                object obj = ResourceManager.GetObject("borrar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap botella {
            get {
                object obj = ResourceManager.GetObject("botella", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap botella_cerveza_quilmes_900x900 {
            get {
                object obj = ResourceManager.GetObject("botella-cerveza-quilmes-900x900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap botonApagado1 {
            get {
                object obj = ResourceManager.GetObject("botonApagado1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap botonApagado2 {
            get {
                object obj = ResourceManager.GetObject("botonApagado2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BotonesAzul {
            get {
                object obj = ResourceManager.GetObject("BotonesAzul", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Brochet {
            get {
                object obj = ResourceManager.GetObject("Brochet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtnC {
            get {
                object obj = ResourceManager.GetObject("BtnC", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtnD {
            get {
                object obj = ResourceManager.GetObject("BtnD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtnH {
            get {
                object obj = ResourceManager.GetObject("BtnH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BtnPizza {
            get {
                object obj = ResourceManager.GetObject("BtnPizza", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Caja_Registradora1 {
            get {
                object obj = ResourceManager.GetObject("Caja-Registradora1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Caja_Registradora2 {
            get {
                object obj = ResourceManager.GetObject("Caja-Registradora2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Caja1 {
            get {
                object obj = ResourceManager.GetObject("Caja1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Caja2 {
            get {
                object obj = ResourceManager.GetObject("Caja2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Cake_ChocolateCake_26374 {
            get {
                object obj = ResourceManager.GetObject("Cake_ChocolateCake_26374", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap carta_de_precentacion {
            get {
                object obj = ResourceManager.GetObject("carta de precentacion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap carta1 {
            get {
                object obj = ResourceManager.GetObject("carta1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap carta2 {
            get {
                object obj = ResourceManager.GetObject("carta2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap carta3 {
            get {
                object obj = ResourceManager.GetObject("carta3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap carta4 {
            get {
                object obj = ResourceManager.GetObject("carta4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap D1 {
            get {
                object obj = ResourceManager.GetObject("D1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap D2 {
            get {
                object obj = ResourceManager.GetObject("D2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap D3 {
            get {
                object obj = ResourceManager.GetObject("D3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap D4 {
            get {
                object obj = ResourceManager.GetObject("D4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap D5 {
            get {
                object obj = ResourceManager.GetObject("D5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap descarga {
            get {
                object obj = ResourceManager.GetObject("descarga", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ensalada {
            get {
                object obj = ResourceManager.GetObject("Ensalada", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ensalada_de_frutas {
            get {
                object obj = ResourceManager.GetObject("ensalada-de-frutas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ensalada1 {
            get {
                object obj = ResourceManager.GetObject("Ensalada1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ensalada2 {
            get {
                object obj = ResourceManager.GetObject("Ensalada2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Ensalada4 {
            get {
                object obj = ResourceManager.GetObject("Ensalada4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ensalada5 {
            get {
                object obj = ResourceManager.GetObject("ensalada5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap flan_casero {
            get {
                object obj = ResourceManager.GetObject("flan-casero", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hambu1 {
            get {
                object obj = ResourceManager.GetObject("Hambu1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hambu2 {
            get {
                object obj = ResourceManager.GetObject("Hambu2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hamburguesaking {
            get {
                object obj = ResourceManager.GetObject("hamburguesaking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HCuádruple {
            get {
                object obj = ResourceManager.GetObject("HCuádruple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap normal15 {
            get {
                object obj = ResourceManager.GetObject("normal15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pago_Tarjeta {
            get {
                object obj = ResourceManager.GetObject("Pago-Tarjeta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pago_Tarjeta2 {
            get {
                object obj = ResourceManager.GetObject("Pago-Tarjeta2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pago_Tarjeta4 {
            get {
                object obj = ResourceManager.GetObject("Pago-Tarjeta4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pescado_frito {
            get {
                object obj = ResourceManager.GetObject("pescado-frito", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pizza {
            get {
                object obj = ResourceManager.GetObject("Pizza", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pizza_margarita_h5fr {
            get {
                object obj = ResourceManager.GetObject("pizza-margarita_h5fr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pizza1 {
            get {
                object obj = ResourceManager.GetObject("pizza1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pizza3 {
            get {
                object obj = ResourceManager.GetObject("Pizza3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pizzaDos {
            get {
                object obj = ResourceManager.GetObject("pizzaDos", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pollo {
            get {
                object obj = ResourceManager.GetObject("Pollo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap producto_ensaladas {
            get {
                object obj = ResourceManager.GetObject("producto-ensaladas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Rabas {
            get {
                object obj = ResourceManager.GetObject("Rabas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap spaghettis {
            get {
                object obj = ResourceManager.GetObject("spaghettis", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TheNote_McDonalds {
            get {
                object obj = ResourceManager.GetObject("TheNote_McDonalds", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tickets {
            get {
                object obj = ResourceManager.GetObject("tickets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tickets1 {
            get {
                object obj = ResourceManager.GetObject("tickets1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Trash1 {
            get {
                object obj = ResourceManager.GetObject("Trash1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Trash2 {
            get {
                object obj = ResourceManager.GetObject("Trash2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
