//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ejercicio5_2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ejercicio5_2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1332919_verduleria_y_fruteria_coquito_e_hijos_fondo_w1900 {
            get {
                object obj = ResourceManager.GetObject("1332919-verduleria-y-fruteria-coquito-e-hijos-fondo.w1900", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Guia_N4___Introduccion_a_las_herramientas {
            get {
                object obj = ResourceManager.GetObject("Guia_N4_-_Introduccion_a_las_herramientas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GULLON_07_ARTICLE_frutas_verduras_verano_web {
            get {
                object obj = ResourceManager.GetObject("GULLON_07_ARTICLE_frutas-verduras-verano-web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_apple_juice_apple_juice_fruit_graphy_juice_natural_foods_food_grape_superfood_clipart_thumb {
            get {
                object obj = ResourceManager.GetObject("png-apple-juice-apple-juice-fruit-graphy-juice-natural-foods-food-grape-superfood" +
                        "-clipart-thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_aroma_grape_vegetable_marjoram_fruit_grape_natural_foods_food_blueberry_oil_clipart_thumb {
            get {
                object obj = ResourceManager.GetObject("png-aroma-grape-vegetable-marjoram-fruit-grape-natural-foods-food-blueberry-oil-c" +
                        "lipart-thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_chef_s_knife_vegetable_food_knife_natural_foods_kitchen_food_cooking_clipart_thumb {
            get {
                object obj = ResourceManager.GetObject("png-chef-s-knife-vegetable-food-knife-natural-foods-kitchen-food-cooking-clipart-" +
                        "thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_cherry_tomato_italian_cuisine_campari_tomato_plum_tomato_vegetable_vegetable_natural_foods_food_tomato_nightshade_family_clipart_thumb {
            get {
                object obj = ResourceManager.GetObject("png-cherry-tomato-italian-cuisine-campari-tomato-plum-tomato-vegetable-vegetable-" +
                        "natural-foods-food-tomato-nightshade-family-clipart-thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_tomato_vegetable_fruits_et_legumes_lycopersicon_verdura_natural_foods_food_nightshade_family_fruit_clipart {
            get {
                object obj = ResourceManager.GetObject("png-tomato-vegetable-fruits-et-legumes-lycopersicon-verdura-natural-foods-food-ni" +
                        "ghtshade-family-fruit-clipart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_vegetarian_cuisine_orange_juice_fruit_mandarin_orange_orange_natural_foods_food_cloud_citrus_clipart_thumb {
            get {
                object obj = ResourceManager.GetObject("png-vegetarian-cuisine-orange-juice-fruit-mandarin-orange-orange-natural-foods-fo" +
                        "od-cloud-citrus-clipart-thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_wild_strawberry_banana_split_fruit_sundae_strawberry_natural_foods_frutti_di_bosco_food_strawberries_clipart_thumb {
            get {
                object obj = ResourceManager.GetObject("png-wild-strawberry-banana-split-fruit-sundae-strawberry-natural-foods-frutti-di-" +
                        "bosco-food-strawberries-clipart-thumb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngflow_com {
            get {
                object obj = ResourceManager.GetObject("pngflow.com", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngflow_com__1_ {
            get {
                object obj = ResourceManager.GetObject("pngflow.com (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngflow_com__2_ {
            get {
                object obj = ResourceManager.GetObject("pngflow.com (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngflow_com__3_ {
            get {
                object obj = ResourceManager.GetObject("pngflow.com (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngflow_com__4_ {
            get {
                object obj = ResourceManager.GetObject("pngflow.com (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap programming_for_kids {
            get {
                object obj = ResourceManager.GetObject("programming-for-kids", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
